docs: 📚 syn-radio-group docs tokens
SickDesignSystem/synergy pull request #119
Opened 2023-11-06 16:05 UTC by LeaLeRose

## ✅ Checklist

- [ ] I have tested my changes manually.
- [ ] I have added automatic tests for my changes (unit- and visual regression tests).
- [ ] I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).
- [ ] I have made sure to follow the projects coding and contribution guides.
- [ ] I have made sure that the bundle size has changed appropriately.
- [ ] I have validated that there are no accessibility errors.
- [ ] I have used design tokens instead of fix css values

2023-11-06 17:14 UTC, schilchSICKAG requested changes

2023-11-06 17:14 UTC, schilchSICKAG commented on packages/tokens/src/figma-tokens/$metadata.json
> +    "toggels",
Think that should be spelled toggles instead of toggels.

2023-11-06 17:14 UTC, schilchSICKAG commented on packages/tokens/src/figma-tokens/$themes.json
> +      "toggels": "disabled",
Think that should be spelled toggles instead of toggels.

2023-11-06 17:14 UTC, schilchSICKAG commented on packages/tokens/src/figma-tokens/$themes.json
> +      "toggels": "disabled",
Think that should be spelled toggles instead of toggels.

2023-11-06 17:14 UTC, schilchSICKAG commented on packages/tokens/src/figma-tokens/$themes.json
> +      "toggels": "disabled",
Think that should be spelled toggles instead of toggels.

2023-11-06 17:14 UTC, schilchSICKAG commented on packages/tokens/src/figma-tokens/$themes.json
> +      "toggels": "source",
Think that should be spelled toggles instead of toggels.

2023-11-06 17:14 UTC, schilchSICKAG commented on packages/tokens/src/figma-tokens/toggels.json
Think that should be spelled toggles instead of toggels.

2023-11-07 08:09 UTC, mariohamann commented on packages/tokens/src/figma-tokens/$metadata.json
> +    "toggles",
I would expect that to be semantic/button and semantic/toggles?

2023-11-07 12:57 UTC, LeaLeRose commented
this should be fine now :) please check again

2023-11-07 14:57 UTC, mariohamann approved these changes

2023-11-07 14:58 UTC, schilchSICKAG approved these changes

2023-11-07 15:05 UTC, merged