feat: ✨ add syn-textarea
SickDesignSystem/synergy pull request #122
Opened 2023-11-08 14:25 UTC by Gwenevere

# Pull Request

## 📖 Description

The syn-textarea is a form field used to input multi-line text.
This PR serves as a way to add the syn-textarea component with the new styling to the component library.

### 🎫 Issues

* https://github.com/SickDesignSystem/synergy/issues/75

## 👩‍💻 Reviewer Notes

* I recommend that this is looked at by @LeaLeRose and @eileenwegner to make sure the design and functionalities are correct and work as expected.

## ✅ Checklist

- [ ] I have tested my changes manually.
- [ ] I have added automatic tests for my changes (unit- and visual regression tests).
- [ ] I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).
- [ ] I have made sure to follow the projects coding and contribution guides.
- [ ] I have made sure that the bundle size has changed appropriately.
- [ ] I have validated that there are no accessibility errors.
- [ ] I have used design tokens instead of fix css values

2023-11-16 11:47 UTC, schilchSICKAG requested changes

2023-11-16 11:47 UTC, schilchSICKAG commented on packages/components/src/synergy.ts
Please make sure to always export the components that you have written, else build will break because of generation of component wrappers trying to import the classes :(

2023-11-16 11:50 UTC, schilchSICKAG commented on packages/components/scripts/vendorism.js
> +const events = [
Just done it and reverted those changes from `vendorism.js` to make it work correctly.

2023-11-16 11:59 UTC, Gwenevere commented on packages/components/src/synergy.ts
done. And I'll keep that in mind for the future components

2023-11-16 12:02 UTC, schilchSICKAG commented on packages/components/src/synergy.ts
I will create a ticket so we will have this as an export job that does it automatically in the future. Because I also tend do forget it ;)

2023-11-16 12:05 UTC, schilchSICKAG commented on packages/components/src/synergy.ts
Just created a new issue for this at https://github.com/SickDesignSystem/synergy/issues/146

2023-11-17 11:00 UTC, Gwenevere commented on packages/components/src/components/input/input.test.ts
> +            <syn-textarea name="g" value="7"></syn-textarea>
I am not really sure,  Mario did the vendorism for the textarea

2023-11-17 11:42 UTC, schilchSICKAG commented on packages/components/src/components/input/input.test.ts
> +            <syn-textarea name="g" value="7"></syn-textarea>
Could you please check back on him? Don´t know if this is an error or should be there.

2023-11-17 13:33 UTC, mariohamann commented on packages/components/src/components/input/input.test.ts
> +            <syn-textarea name="g" value="7"></syn-textarea>
This is correct. Initially it was `syn-textarea` but this lead to failing tests, that't why I renamed it to `syn-input`. Now we have it and we can run the original test again. :)

2023-11-17 13:33 UTC, mariohamann commented on packages/components/src/components/input/input.test.ts
> +            <syn-textarea name="g" value="7"></syn-textarea>
See here: https://github.com/SickDesignSystem/synergy/pull/122/files#diff-4fafadbddfc8014b397c05b8a31552932283b43ada2db16e8621bc8bc8745183L39

2023-11-17 13:34 UTC, mariohamann commented on packages/components/src/components/input/input.test.ts
> +            <syn-textarea name="g" value="7"></syn-textarea>
If you're working on the syn-checkbox you can do the same thing here.

2023-11-20 06:25 UTC, schilchSICKAG approved these changes

2023-11-20 07:49 UTC, merged