docs: 📚 add docs for syn-switch
SickDesignSystem/synergy pull request #127
Opened 2023-11-09 16:43 UTC by LeaLeRose

## ✅ Checklist

- [ ] I have tested my changes manually.
- [ ] I have added automatic tests for my changes (unit- and visual regression tests).
- [ ] I have updated the project documentation to reflect my changes (e.g. CHANGELOG, Storybook, ...).
- [ ] I have made sure to follow the projects coding and contribution guides.
- [ ] I have made sure that the bundle size has changed appropriately.
- [ ] I have validated that there are no accessibility errors.
- [ ] I have used design tokens instead of fix css values

2023-11-10 06:50 UTC, schilchSICKAG requested changes

2023-11-10 06:50 UTC, schilchSICKAG commented on packages/tokens/src/figma-tokens/_docs.json
> +          "title": "[object Object]",
This seems to be kind of wrong. Object Object is often seen in JavaScript when using something like `{ hello: 'world' }`. Maybe check the syntax in Figma?

2023-11-13 12:47 UTC, mariohamann approved these changes

2023-11-13 12:49 UTC, mariohamann approved these changes

2023-11-13 12:51 UTC, merged