revised github templates
SickDesignSystem/synergy pull request #70
Opened 2023-10-16 06:10 UTC by klaarseSICKAG

# Pull Request

## 📖 Description

We decided to revise github templates for this repo

### 🎫 Issues

https://github.com/SickDesignSystem/Internal/issues/4

2023-10-16 06:55 UTC, schilchSICKAG requested changes

2023-10-16 06:55 UTC, schilchSICKAG commented on .github/ISSUE_TEMPLATE/component-request-new-component.md
> +- [ ] I have looked at the documentation site and was not able to find the component. <!-- link zur seite??? -->
Please remove comment before pushing :)

2023-10-16 06:55 UTC, schilchSICKAG commented on .github/ISSUE_TEMPLATE/component-request-new-component.md
> +- [ ] I have looked at the documentation site and was not able to find the component. <!-- link zur seite??? -->
Site URL will be available in the local Documentation (e.g. README.md) when ready.

2023-10-16 06:55 UTC, schilchSICKAG commented on .github/ISSUE_TEMPLATE/component-request-new-component.md
> +- [ ] I have looked into the Figma boards and was not able to find the component. <!-- kommt jeder auf figma??? -->
There will be a public Figma board later (I assume). A link will also be part of the documentation. Please remove comment before pushing ;)

2023-10-16 06:55 UTC, schilchSICKAG commented on .github/ISSUE_TEMPLATE/component-request-new-component.md
> +**Description**
I would suggest adding a whitespace here

2023-10-16 06:55 UTC, schilchSICKAG commented on .github/ISSUE_TEMPLATE/generic-bug.md
> +- [ ] I have verified the bug exists in the latest version of `@synergy-design-system/core` (e.g. via `npm install @synergy-design-system/core@latest`). <!-- core??? -->
Good catch ;). Seems like a leftover from the original version. Should be `@synergy-design-system/components`.

2023-10-18 10:01 UTC, schilchSICKAG submitted a review, later dismissed

2023-10-18 11:59 UTC, mariohamann commented
I see a valid use case for the checkboxes at the beginning for externals, but question this if it helps for our current process in our team. But I don't have strong opinions on that.
---

I personally would like to have "Rationale" at the beginning and explicitly rename it to "User Story" and provide a sample text we can edit.

Something like this:
> As a [PERSONA] of the Synergy Design System, I would like to [REQUIRE], as well as [FURTHER_REQUIREMENT], so that [PRODUCT_VALUE], and [FURTHER_PRODUCT_VALUE].

This helps especially in Refinements to get a common understanding why we're doing things.

2023-10-18 12:03 UTC, mariohamann commented
I'm missing a `chore` template. Currently all templates force us to new version numbers. Sometimes we have just stuff going on inside our repo that doesn't change any output, shouldn't bump a version and especially shouldn't add stuff to the changelog.

2023-10-27 08:42 UTC, schilchSICKAG commented
I have just merged back main into this branch and created a stale issue template for chores. @klaarseSICKAG: You could use this as a starting point for formulating a good template. I also think @mariohamann is right about the rationale: We have the chance to create a clean template that guides the user in creating issues, so it would be the right time to include something like this in the template.

2023-11-06 09:52 UTC, schilchSICKAG requested changes

2023-11-06 09:52 UTC, schilchSICKAG commented on .github/ISSUE_TEMPLATE/generic-docs.md
>  **Rationale**:
You have used `# HEADLINE` semantics in other templates, I think we should either use the current version (`**HEADLINE**:`) or the new version (`# HEADLINE`) in all templates.

2023-11-06 10:27 UTC, schilchSICKAG approved these changes

2023-11-06 10:39 UTC, merged